package io.github.aigoodle.workflow.node;

import io.github.aigoodle.workflow.chat.ChatStreamSink;
import io.github.aigoodle.workflow.engine.RunCancellationToken;
import io.github.aigoodle.workflow.variable.VariablePool;
import lombok.Data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.function.BiConsumer;

/**
 * Per-run state shared with every node executor: the variable pool plus run-level
 * identifiers and a step recorder for observability.
 */
@Data
public class ExecutionContext {

    private final VariablePool pool = new VariablePool();
    private String runId;
    private String conversationId;
    private String tenantId;
    private String userId;
    private RunCancellationToken cancellationToken;
    private Map<String, Object> iterationCursors = new java.util.concurrent.ConcurrentHashMap<>();
    private BiConsumer<String, Object> iterationProgressListener = (nodeId, cursor) -> {};

    public Object iterationCursor(String nodeId) { return iterationCursors.get(nodeId); }

    public void checkpointIteration(String nodeId, Object cursor) {
        iterationCursors.put(nodeId, cursor);
        iterationProgressListener.accept(nodeId, cursor);
    }

    public void throwIfCancelled() {
        if (cancellationToken != null) cancellationToken.throwIfCancelled();
    }

    /** The inputs the workflow was started with (seeded by the START node). */
    private final Map<String, Object> inputs = new HashMap<>();

    private final List<StepRecord> steps = new ArrayList<>();

    /**
     * Optional token sink threaded from the outer caller (e.g.
     * {@code WorkflowChatGenerator} for SSE chat). Non-null +
     * {@link ChatStreamSink#isStreaming()} = LLM nodes switch to
     * {@code spec.stream().content()} and ANSWER nodes subscribe live;
     * null = classic blocking mode.
     */
    private ChatStreamSink chatSink;

    public static ExecutionContext start(Map<String, Object> inputs, String conversationId,
                                         ChatStreamSink chatSink) {
        return start(inputs, conversationId, chatSink, null);
    }

    public static ExecutionContext start(Map<String, Object> inputs, String conversationId,
                                         ChatStreamSink chatSink, String requestedRunId) {
        ExecutionContext context = new ExecutionContext();
        context.runId = requestedRunId == null ? UUID.randomUUID().toString() : requestedRunId;
        context.conversationId = conversationId;
        context.chatSink = chatSink;
        if (inputs != null) {
            context.inputs.putAll(inputs);
            inputs.forEach(context.pool::setSystem);
            // The visual designer exposes START/input values under `var.*`.
            // Keep `sys.*` as the canonical engine namespace and provide this
            // compatibility alias so templates generated by the UI resolve.
            context.pool.putAll("var", inputs);
        }
        return context;
    }

    public void record(StepRecord step) {
        steps.add(step);
    }
}
